In [ ]:
import numpy as np

# Creating arrays from Existing Data

In [ ]:
numbers = np.array([2,3,5,7,11])
numbers

array([ 2,  3,  5,  7, 11])

In [ ]:
type(numbers)

numpy.ndarray

Multidimensional Arguments

In [ ]:
#1D array
array_1D = np.array([2,4,5,6])
array_1D

array([2, 4, 5, 6])

In [ ]:
#2D array
a = [[1,2,3],
    [1,2,3],
    [1,2,3]]
for i in a:
    for j in i:
        print(j)

1
2
3
1
2
3
1
2
3


In [ ]:
array_2D = np.array([[2,4,5,6],
                   [2,4,5,6],
                   [2,4,5,6]])
array_2D

array([[2, 4, 5, 6],
       [2, 4, 5, 6],
       [2, 4, 5, 6]])

In [ ]:
#3D array
a = [[[1,2,3],
    [1,2,3]],
    [[1,2,3],
    [1,2,3]]]
len(a)

2

In [ ]:
array_3D = np.array([[[2,4,5,6],[2,4,5,6],[2,4,5,6]]])
array_3D

array([[[2, 4, 5, 6],
        [2, 4, 5, 6],
        [2, 4, 5, 6]]])

# Problem 1

Create a two-dimensional array from a list comprehension that produces the even integers from 2 through 20 in the first row and the odd integers from 1 through 21 in the second row.

In [ ]:
arr = np.array([[i for i in range(2,21,2)],[i for i in range(1,22,2)]])
arr

<ipython-input-14-165c81b4bfa7>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[i for i in range(2,21,2)],[i for i in range(1,22,2)]])


array([list([2, 4, 6, 8, 10, 12, 14, 16, 18, 20]),
       list([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21])], dtype=object)

# Array Attributes

In [ ]:
floats = np.array([0.0,0.1,0.2,0.3])
floats

array([0. , 0.1, 0.2, 0.3])

In [ ]:
integers = np.array([[1,2,3],[4,5,6],[7,8,9]])
integers

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
strings = np.array(['apple','big','cat'])
strings

array(['apple', 'big', 'cat'], dtype='<U5')

# Checking an array's element types

In [ ]:
type(32)

int

In [ ]:
floats.dtype

dtype('float64')

In [ ]:
integers.dtype

dtype('int32')

In [ ]:
strings.dtype

dtype('<U5')

#checking an array's dimentions & shape

In [ ]:
array_1D.ndim

1

In [ ]:
array_2D.ndim

2

In [ ]:
array_3D.ndim

3

In [ ]:
integers.ndim

2

In [ ]:
len(array_3D)

1

In [ ]:
array_3D.shape

(1, 3, 4)

In [ ]:
array_2D.shape

(3, 4)

#Checking an array's Number of Elements and Element size

In [ ]:
integers.size

9

In [ ]:
array_3D.size

12

In [ ]:
integers.itemsize

4

In [ ]:
floats.size

4

In [ ]:
floats.itemsize

8

In [ ]:
strings.size

3

In [ ]:
strings.itemsize

20

In [ ]:
arr = np.array(['tokyo','dhaka','newyork was never'])
arr

array(['tokyo', 'dhaka', 'newyork was never'], dtype='<U17')

# Array Operators

In [ ]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [ ]:
x+10 #scalar addition is element wise

array([10, 11, 12, 13, 14])

In [ ]:
x*2 #scalar multiplication is element wise

array([0, 2, 4, 6, 8])

In [ ]:
x+x #array addition is element wise

array([0, 2, 4, 6, 8])

In [ ]:
x*x #array multiplication is element wise

array([ 0,  1,  4,  9, 16])

In [ ]:
x/10 #array division is element wise

array([0. , 0.1, 0.2, 0.3, 0.4])

In [ ]:
x//10

array([0, 0, 0, 0, 0], dtype=int32)

In [ ]:
2*3

6

In [ ]:
x**3

array([ 0,  1,  8, 27, 64], dtype=int32)

In [ ]:
x = np.array([[11,9,11],[2,15,18]])

In [ ]:
x>10

array([[ True, False,  True],
       [False,  True,  True]])

In [ ]:
x>=10

array([[ True, False,  True],
       [False,  True,  True]])

In [ ]:
x<10

array([[False,  True, False],
       [ True, False, False]])

In [ ]:
x<=10

array([[False,  True, False],
       [ True, False, False]])

In [ ]:
x==9

array([[False,  True, False],
       [False, False, False]])

In [ ]:
x!=11

array([[False,  True, False],
       [ True,  True,  True]])

# Numpy Methods

In [ ]:
grades = np.array([[87,96,70],[100,87,90],[94,77,90],[100,81,82]])
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [ ]:
grades.max()

100

In [ ]:
grades.min()

70

In [ ]:
grades.sum()

1054

In [ ]:
grades.std()

8.792357792739987

In [ ]:
grades.mean()

87.83333333333333

In [ ]:
grades.var()

77.30555555555556

In [ ]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

In [ ]:
import copy

li1 = [1,2,[3,5],4]

In [ ]:
li2 = copy.deepcopy(li1)

In [ ]:
li2

[1, 2, [3, 5], 4]

In [ ]:
li1

[1, 2, [3, 5], 4]

In [ ]:
li2[2][0]='z'

In [ ]:
li2

[1, 2, ['z', 5], 4]

In [ ]:
li1

[1, 2, [3, 5], 4]